import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-flora-bg dark:bg-flora-darkBg text-flora-soil font-scientific min-h-screen">
        <header className="w-full py-4 px-6 border-b border-flora-leaf bg-flora-light dark:bg-flora-darkBg flex items-center justify-between">
          <span className="font-scientific text-2xl font-bold text-flora-leaf">Flora-Science</span>
          <nav aria-label="Main navigation" className="flex gap-6">
            <Link href="/dashboard" className="text-flora-leaf hover:text-flora-accent font-semibold transition-calm">Dashboard</Link>
            <Link href="/plants" className="text-flora-leaf hover:text-flora-accent font-semibold transition-calm">Plants</Link>
            <Link href="/science/experiments" className="text-flora-leaf hover:text-flora-accent font-semibold transition-calm">Science</Link>
          </nav>
        </header>
        <main className="max-w-4xl mx-auto py-8 px-4">
          {children}
        </main>
        <footer className="w-full py-4 px-6 border-t border-flora-leaf bg-flora-light dark:bg-flora-darkBg text-xs text-flora-soil text-center mt-8">
          &copy; {new Date().getFullYear()} Flora-Science. Built for scientific clarity and plant wellness.
        </footer>
      </body>
    </html>
  );
}
